fn main(
    x1: pub Field,
    x2: pub Field,
    x3: pub Field,
    x4: pub Field,
    x5: pub Field,
    x6: pub Field,
    x7: pub Field,
    x8: pub Field,
    x9: pub Field,
    x10: pub Field,
    x11: pub Field,
    ){
   assert(x1==0);
   assert(x2==0);
   assert(x3==0);
   assert(x4==0);
   assert(x5==0);
   assert(x6==0);
   assert(x7==0);
   assert(x8==0);
   assert(x9==0);
   assert(x10==0);
   assert(x11==0);
}

